@server = https://shiny-space-fiesta-7v9rx477x45w26qp-8080.app.github.dev
###
GET {{server}}/api/cursos
###
POST {{server}}/api/cursos
Content-Type: application/json

{"nombre": "Gestion de la Creatividad", "materia": "Social", "descripcion": "1 Creditos"}
###
GET {{server}}/api/alumnos
###
POST {{server}}/api/alumnos
Content-Type: application/json

{"nombre": "Joaquín"}



